### ISSUE TITLE
gitbook的部分页面链接失效

### ISSUE THREAD

**Issue by qci133** [hsz1273327/TutorialForPython#4]
例如，http://blog.hszofficial.site/TutorialForPython/语法篇/ 这个页面可以打开，但点击这个页面的右侧的“下一页”箭头，是打不开下一页的。同时，在左侧目录栏中右键“Python的数据类型”，选择“在新标签页中打开链接”，是 404（URL 为 http://blog.hszofficial.site/TutorialForPython/语法篇/Python的数据模型/Python的数据模型/）
前面一小部分页面都可以正常访问，后面一大半的页面都是一样的 404. 不知道是我网络问题，还是生成的 book 内的链接没搞对。

**Comment by hsz1273327** [comment]
我这边试了下语法篇部分确实有这个问题,但后面大多都可以正常显示.这边也会尽快修复,感谢

Regards

HSZ.

Tel: +86 15851390734
E-mail: hsz1273327@gmail.com
github: https://github.com/hsz1273327
website: http://blog.hszofficial.site/
Please consider the environment before printing this email.



QIAN CHENG <notifications@github.com> 于2019年4月27日周六 下午2:54写道：

**Comment by qci133** [comment]
赞高效。看起来今天已经修复完成了。现在随机点击一些链接都能访问。

**Comment by hsz1273327** [comment]
之前是因为应为字母大小写的问题,似乎github托管的服务器不区分大小写

Regards

HSZ.

Tel: +86 15851390734
E-mail: hsz1273327@gmail.com
github: https://github.com/hsz1273327
website: http://blog.hszofficial.site/
Please consider the environment before printing this email.



QIAN CHENG <notifications@github.com> 于2019年4月28日周日 上午9:26写道：
